#!/bin/bash

# ***********************************************
#  Seup Zabbix 3.4
#  Date: 07.09.2017
#  v1.00
#  Authors:
#  Vladimir Svishch (BikerIndian)  <mail:5693031@gmail.com>
#  https://github.com/BikerIndian/Zabbix
# ***********************************************

sudo service zabbix-server start
# Добавляем в автозагрузку
sudo update-rc.d zabbix-server enable

sudo service  apache2 restart

# Получаем рабочий каталог
DIRROOT=$(cd $(dirname $0) && pwd)

# конфигурационный файл
CONFIG=$DIRROOT/zabbix.conf

if ! [ -f $CONFIG ]; then
echo
echo "  Конфигурационный файл"
echo "   $CONFIG"
echo "  не найден!"
exit 1
fi

# Подгружаем конфигурационный файл
. $CONFIG  # после точки пробел!



echo
echo "  **********************************************"
echo "              Zabbix установка    "
echo "  **********************************************"
echo " {HOST}/zabbix/setup.php"
echo " Данные для настройки Zabbix"
echo " HOST = $HOST"
echo " DATABASE = $DATABASE"
echo " USER = $USER"
echo " PASSWORD = $PASSWORD"
echo " -----------------------------------------------"
echo "  Для входа в WEB"
echo
echo " Username = Admin"
echo " Password = zabbix"
echo
echo "Если при настройке PHP option date.timezone Fail"
echo "то сюда -> /etc/php5/apache2/php.ini"
echo "меняем: date.timezone = Europe/Moscow"
